title: Michael Troger
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
website_source_url: https://github.com/michaeltroger/michaeltroger.com
website_source_root_url: https://github.com/michaeltroger/michaeltroger.com/blob/master/docs/
