name: Deploy

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3am

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@v1
