name: screenshots ci actions
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }} 
  cancel-in-progress: true

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Remove old screenshots first
      run: rm -rd screenshots
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: Generate screenshots homepage
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://michaeltroger.com
        devices: iPhone 13
    - name: Keep only few screenshots
      run: |
        mv screenshots screenshots_generated
        mkdir screenshots
        cp screenshots_generated/iPhone* screenshots/home_iphone.jpeg
        cp screenshots_generated/desktopPage1920x1080* screenshots/home_desktop.jpeg
        rm -rd screenshots_generated
    - name: Generate screenshots contact page
      uses: flameddd/screenshots-ci-action@master
      with:
        url: https://michaeltroger.com/contact
        devices: iPhone 13
    - name: Keep only few screenshots
      run: |
        mv screenshots screenshots_generated
        mkdir screenshots
        cp screenshots_generated/iPhone* screenshots/contact_iphone.jpeg
        cp screenshots_generated/desktopPage1920x1080* screenshots/contact_desktop.jpeg
        rm -rd screenshots_generated
    - name: Create screenshot pull request if on master branch
      uses: peter-evans/create-pull-request@v6
      if: github.ref == 'refs/heads/master'
      with:
        branch: feature/update_screenshots
        title: Update of screenshots
        commit-message: Update of screenshots
        add-paths: |
          screenshots/*