name: Update OpenPGP.js

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: git submodule update --rebase --remote

    - uses: actions/setup-node@v4
      with:
        node-version: 21

    - run: npm --prefix openpgpjs install

    - run: cp openpgpjs/dist/openpgp.min.js docs/js/openpgp.min.js
    - run: cp openpgpjs/dist/openpgp.min.js.map docs/js/openpgp.min.js.map

    - name: Open pull request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: feature/update-openpgpjs
        title: Update of OpenPGP.js
        commit-message: Update of OpenPGP.js
        add-paths: |
          docs/js/openpgp.min.js
          docs/js/openpgp.min.js.map
          openpgpjs
